export const TILE_IMAGES = {
  "Neutron Bombs":      require("../../assets/tiles/neutron_bombs.png"),
  "Starbase":           require("../../assets/tiles/starbase.png"),
  "Plasma Cannon":      require("../../assets/tiles/plasma_cannon.png"),
  "Phase Shield":       require("../../assets/tiles/phase_shield.png"),
  "Advanced Mining":    require("../../assets/tiles/advanced_mining.png"),
  "Tachyon Source":     require("../../assets/tiles/tachyon_source.png"),
  "Gluon Computer":     require("../../assets/tiles/gluon_computer.png"),
  "Plasma Missile":     require("../../assets/tiles/plasma_missile.png"),
  "Gauss Shield":       require("../../assets/tiles/gauss_shield.png"),
  "Fusion Source":      require("../../assets/tiles/fusion_source.png"),
  "Improved Hull":      require("../../assets/tiles/improved_hull.png"),
  "Positron Computer":  require("../../assets/tiles/positron_computer.png"),
  "Advanced Economy":   require("../../assets/tiles/advanced_economy.png"),
  "Tachyon Drive":      require("../../assets/tiles/tachyon_drive.png"),
  "Antimatter Cannon":  require("../../assets/tiles/antimatter_cannon.png"),
  "Quantum Grid":       require("../../assets/tiles/quantum_grid.png"),
  "Nanorobots":         require("../../assets/tiles/nanorobots.png"),
  "Fusion Drive":       require("../../assets/tiles/fusion_drive.png"),
  "Orbital":            require("../../assets/tiles/orbital.png"),
  "Advanced Robotics":  require("../../assets/tiles/advanced_robotics.png"),
  "Advanced Labs":      require("../../assets/tiles/advanced_labs.png"),
  "Monolith":           require("../../assets/tiles/monolith.png"),
  "Wormhole Generator": require("../../assets/tiles/wormhole_generator.png"),
  "Artifact Key":       require("../../assets/tiles/artifact_key.png"),
  "Antimatter Splitter":require("../../assets/tiles/antimatter_splitter.png"),
  "Conifold Field":     require("../../assets/tiles/conifold_field.png"),
  "Neutron Absorber":   require("../../assets/tiles/neutron_absorber.png"),
  "Absorption Shield":  require("../../assets/tiles/absorption_shield.png"),
  "Cloaking Device":    require("../../assets/tiles/cloaking_device.png"),
  "Improved Logistics": require("../../assets/tiles/improved_logistics.png"),
  "Sentient Hull":      require("../../assets/tiles/sentient_hull.png"),
  "Soliton Cannon":     require("../../assets/tiles/soliton_cannon.png"),
  "Transition Drive":   require("../../assets/tiles/transition_drive.png"),
  "Warp Portal":        require("../../assets/tiles/warp_portal.png"),
  "Flux Missile":       require("../../assets/tiles/flux_missile.png"),
  "Pico Modulator":     require("../../assets/tiles/pico_modulator.png"),
  "Ancient Labs":       require("../../assets/tiles/ancient_labs.png"),
  "Zero-Point Source":  require("../../assets/tiles/zero_point_source.png"),
  "Metasynthesis":      require("../../assets/tiles/metasynthesis.png"),
};