spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eclipse_db
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8082