spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eclipse_db
    username: postgres
    password: LetMeIn123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8082